name: AutoRelease

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/'+context.sha,
              sha: context.sha
            })
      #- name: Archive production artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: source_code
      #    path: |
      #      .
      #      !.git
      - name: Source code
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'source.zip'
          directory: '.'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "source.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Zip Dist
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'web_app.zip'
          directory: './dist/'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      #- name: Archive production artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: only_compiled_app
      #    path: |
      #      dist
      #      !dist/**/*.md
      #- name: Build
      #  run: echo ${{ github.sha }} > Release.txt
      #- name: Test
      #  run: cat Release.txt
      #- name: Archive Release
      #  uses: thedoctor0/zip-release@0.7.5
      #  with:
      #    type: 'zip'
      #    filename: 'release.zip'
      #    exclusions: '*.git* /*node_modules/* .editorconfig'
      #- name: Upload Release
      #  uses: ncipollo/release-action@v1.12.0
      #  with:
      #    artifacts: "release.zip"
      ##- name: Release
      ##  uses: softprops/action-gh-release@v2
      ##  with:
      ##    files: |
      ##      Release.txt
      ##      LICENSE