name: AutoRelease

on:
  push:
    branches: [ main ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: '0'
      - name: Determine tag name
        id: tag
        shell: bash
        run: |
          BUILD_NUMBER="$(git rev-list --count HEAD)"
          SHORT_HASH="$(git rev-parse --short=7 HEAD)"
          if [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
            echo "name=b${BUILD_NUMBER}" >> $GITHUB_OUTPUT
          else
            SAFE_NAME=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')
            echo "name=${SAFE_NAME}-b${BUILD_NUMBER}-${SHORT_HASH}" >> $GITHUB_OUTPUT
          fi
      - name: Pack artifacts
        id: pack_artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event.inputs.create_release == 'true' }}
        run: |
          zip -r source-${{ steps.tag.outputs.name }}.zip . -x *.git* /*node_modules/* .editorconfig /*dist/*
      - name: Upload artifacts
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event.inputs.create_release == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          path: source-${{ steps.tag.outputs.name }}.zip
          name: source.zip
      #- name: Archive production artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: source_code
      #    path: |
      #      .
      #      !.git
      #- name: Source code
      #  uses: thedoctor0/zip-release@0.7.5
      #  with:
      #    type: 'zip'
      #    filename: 'source.zip'
      #    directory: '.'
      #    exclusions: '*.git* /*node_modules/* .editorconfig'
      #- name: Upload Release
      #  uses: ncipollo/release-action@v1.12.0
      #  with:
      #    artifacts: "source.zip"
      #    token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Pack artifacts2
        id: pack_artifacts2
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event.inputs.create_release == 'true' }}
        run: |
          cd dist
          zip -r ../webapp-${{ steps.tag.outputs.name }}.zip . -x *.git* *.idea* /*node_modules/* .editorconfig
      - name: Upload artifacts2
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event.inputs.create_release == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          path: webapp-${{ steps.tag.outputs.name }}.zip
          name: webapp.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: webapp-${{ steps.tag.outputs.name }}.zip
      #- name: Zip Dist
      #  uses: thedoctor0/zip-release@0.7.5
      #  with:
      #    type: 'zip'
      #    filename: 'web_app.zip'
      #    directory: './dist/'
      #    exclusions: '*.git* /*node_modules/* .editorconfig'
      #- name: Archive production artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: only_compiled_app
      #    path: |
      #      dist
      #      !dist/**/*.md
      #- name: Build
      #  run: echo ${{ github.sha }} > Release.txt
      #- name: Test
      #  run: cat Release.txt
      #- name: Archive Release
      #  uses: thedoctor0/zip-release@0.7.5
      #  with:
      #    type: 'zip'
      #    filename: 'release.zip'
      #    exclusions: '*.git* /*node_modules/* .editorconfig'
      #- name: Upload Release
      #  uses: ncipollo/release-action@v1.12.0
      #  with:
      #    artifacts: "release.zip"
      ##- name: Release
      ##  uses: softprops/action-gh-release@v2
      ##  with:
      ##    files: |
      ##      Release.txt
      ##      LICENSE